# ░░░░░░░░░░░░░░░   SlimeChunkPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/slimechunkplus.86532/
#  Wiki: https://github.com/momoservertw/SlimeChunkPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 2
Check-Updates: true

# Checking the nearby slime chunk.
Slime-Chunk:
  Enable: true
  Succeed:
    Message: true
    # Sending nearby slime chunks information.
    Nearby-Information:
      Enable: true
      # Unit: chunk
      Range: 3
    Commands:
      - "sound: Succeed"
      - "sound: SlimeJump"
      - "particle: Slime"
    # To display current chunk by Selection Visualizer.
    #  - "op: svis chunk"
  Failed:
    Message: true
    Commands:
      - "sound: Failed"
      - "particle: Flame"

Message:
  prefix: "&f[&aSLP&f] &r"
  Commands:
    title: "&8▩▩▩▩▩▩▩▩▩▩ &dSlimeChunkPlus &8▩▩▩▩▩▩▩▩▩▩"
    help: "&f/scp help &8- &7This help menu."
    reload: "&f/scp reload &8- &7Reloads config file."
    version: "&f/scp version &8- &7Checks the plugin version and updates."
    checkslime: "&f/scp checkslime &8- &7To get the information of slime chunks."
    checkslimeOther: "&f/scp checkslime [player] &8- &7To get the information of slime chunks for other player."
  slimeChunkFound: "&aYou are standing on a slime chunk."
  slimeChunkNotFound: "&fYou are not standing on a slime chunk."
  slimeChunkNearInfo: "&eThere are &6%amount% slime blocks &enearby you. &7(Distance: %distance% blocks)"
  slimeChunkNearInfoNull: "&cThere is no slime chunks nearby you."