name: SlimeChunkPlus
main: tw.momocraft.slimechunkplus.SlimeChunkPlus
author: Momocraft
api-version: 1.13
version: 1.0.1
description: Best slime chunk checking plugin! Executing custom command and show particle.
softdepend: [Vault, PlayerPoints, PlaceHolderAPI]

commands:
  slimechunkplus:
    description: Displays main command menu.
    permission: slimechunkplus.use
    aliases: [ scp ]
    usage: |
      /slimechunkplus

permissions:
  slimechunkplus.*:
    description: Allows use of all commands and feature.
    default: op
    children:
      slimechunkplus.use: true
      SlimeChunkPlus.command.*: true
  slimechunkplus.use:
    description: Allows use of basic commands.
    default: true
  slimechunkplus.command.*:
    description: Allows use all commands.
    default: op
    children:
      slimechunkplus.command.reload: true
      slimechunkplus.command.version: true
      slimechunkplus.command.slimecheck: true
  slimechunkplus.command.reload:
    description: Allows use of /slimechunkplus command reload.
    default: op
  slimechunkplus.command.version:
    description: Allows use of command /slimechunkplus version.
    default: op
  slimechunkplus.command.slimecheck:
    description: Allows use of command /slimechunkplus slimecheck.
    default: op