name: SlimeChunkPlus
main: tw.momocraft.slimechunkplus.SlimeChunkPlus
author: Momocraft
api-version: 1.13
version: 1.0.0
description: Controling inventory.
softdepend: [ ]

commands:
  slimechunkplus:
    description: Displays main command menu.
    permission: slimechunkplus.use
    aliases: [ itp ]
    usage: |
      /slimechunkplus

permissions:
  slimechunkplus.*:
    description: Allows use of all commands and feature.
    default: op
    children:
      slimechunkplus.use: true
      SlimeChunkPlus.command.*: true
  slimechunkplus.use:
    description: Allows use of basic commands.
    default: true
  slimechunkplus.command.*:
    description: Allows use all commands.
    default: op
    children:
      slimechunkplus.command.reload: true
      slimechunkplus.command.version: true
      slimechunkplus.command.clear: true
      slimechunkplus.command.clear.other: true
      slimechunkplus.command.cleanslot: true
      slimechunkplus.command.cleanslot.oter: true
      slimechunkplus.command.takeoff: true
      slimechunkplus.command.takeoff.other: true
      slimechunkplus.command.takeoffslot: true
      slimechunkplus.command.takeoffslot.oter: true
  slimechunkplus.command.reload:
    description: Allows use of /SlimeChunkPlus command reload.
    default: op
  slimechunkplus.command.version:
    description: Allows use of command /SlimeChunkPlus version.
    default: op
  slimechunkplus.command.clear:
    description: Allows use of command /SlimeChunkPlus clear.
    default: op
  slimechunkplus.command.clear.other:
    description: Allows use of command /SlimeChunkPlus clear PLAYER.
    default: op
  slimechunkplus.command.cleanslot:
    description: Allows use of command /SlimeChunkPlus cleanslot.
    default: op
  slimechunkplus.command.cleanslot.other:
    description: Allows use of command /SlimeChunkPlus cleanslot PLAYER.
    default: op
  slimechunkplus.command.takeoff:
    description: Allows use of command /SlimeChunkPlus takeoff.
    default: op
  slimechunkplus.command.takeoff.other:
    description: Allows use of command /SlimeChunkPlus takeoff PLAYER.
    default: op
  slimechunkplus.command.takeoffslot:
    description: Allows use of command /SlimeChunkPlus takeoffslot.
    default: op
  slimechunkplus.command.takeoffslot.other:
    description: Allows use of command /SlimeChunkPlus takeoffslot PLAYER.
    default: op