# ░░░░░░░░░░░░░░░   SlimeChunkPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/slimechunkplus.86532/
#  Wiki: https://github.com/momoservertw/SlimeChunkPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 2

# Checking the nearby slime chunk.
Slime-Chunk:
  Enable: true
  Succeed:
    Message: true
    # Sending nearby slime chunks information.
    Nearby-Information:
      Enable: true
      # Unit: chunk
      Range: 3
    Commands:
      - "message: &fYou are not standing on a slime chunk."
      - "sound-group: Succeed"
      - "sound: -s:ENTITY_SLIME_JUMP -t:8 -i:20"
      - "particle: -p:SLIME -t:8 -i:20"
    # To display current chunk by Selection Visualizer.
    #  - "op: svis chunk"
  Failed:
    Message: true
    Commands:
      - "message: &aYou are standing on a slime chunk."
      - "sound: -s:ENTITY_VILLAGER_HURT -t:2 -i:20"
      - "particle: -p:EXPLOSION_HUGE -t:2 -i:20"