# ░░░░░░░░░░░░░░░   SlimeChunkPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/slimechunkplus.86532/
#  Wiki: https://github.com/momoservertw/SlimeChunkPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 1
Check-Updates: true
Debugging: false

General:
  Settings:
    Features:
      # Changed these options need to restart the server.
      Hook:
        Vault: true
        PlayerPoints: true
        PlaceHolderAPI: true
  # The settings for custom sounds.
  # More information: https://github.com/momoservertw/SlimeChunkPlus/wiki/Custom-Sounds
  Sounds:
    Succeed:
      Type: ENTITY_PLAYER_LEVELUP
    Failed:
      Type: ENTITY_SHULKER_HURT
    SlimeJump:
      Type: ENTITY_SLIME_JUMP
      Loop:
        Times: 8
        Interval: 20
  # The settings for custom particles.
  # More information: https://github.com/momoservertw/SlimeChunkPlus/wiki/Custom-Particles
  Particles:
    Slime:
      Type: SLIME
      Amount: 3
      Times: 8
      Interval: 20
    Flame:
      Type: FLAME
      Amount: 3
      Times: 8
      Interval: 20
  # The settings for custom commands.
  # More information: https://github.com/momoservertw/SlimeChunkPlus/wiki/Custom-Commands
  Custom-Commands:
    Settings:
      Log:
        Default:
          # Creating new file if the modified date is difference.
          New-File: true
          To-Zip: true
        Custom:
          New-File: false
          To-Zip: true
          Path: "plugin//CustomLogs"
          Name: "latest"
    # To send frequently used commands with placeholders.
    Groups:
      reward: "message: &6&lReward&c✤ &f%cmd_arg1%"
      awards: "message: &d✧ &f%cmd_arg1% &d✧"
      cgl: "broadcast: &6Congratulate &e%player% &6use &f%cmd_arg1% &8- &6Get the %cmd_arg2% &7<&f%cmd_arg3%&7>"
      money: "console: money give %player% %cmd_arg1%"\

# Checking the nearby slime chunk.
# More information: https://github.com/momoservertw/SlimeChunkPlus/wiki/Slime-Chunk
Slime-Chunk:
  Enable: true
  Succeed:
    Message: true
    # Sending nearby slime chunks information.
    Nearby-Information:
      Enable: true
      # Unit: chunk
      Range: 3
    Commands:
      - "sound: Succeed"
      - "sound: SlimeJump"
      - "particle: Slime"
    # To display current chunk by Selection Visualizer.
    #  - "op: svis chunk"
  Failed:
    Message: true
    Commands:
      - "sound: Failed"
      - "particle: Flame"

Message:
  prefix: "&a&l黏液檢測器&4&l〄 &r"
  noPermission: "&cYou do not have permission to use that command!"
  configReload: "&aConfiguration(s) Reloaded!"
  unknownCommand: "&cUnknown command, See &e/SlimeChunkPlus help &cfor a list of commands."
  targetNotFound: "&cThe player %targetplayer% could not be found!"
  featureDisabled: "&cThe feature is disabled."
  onlyPlayer: "&cThis command can only executing from player."
  SlimeChunkPlus:
    Commands:
      title: "&8▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩ &dSlimeChunkPlus &8▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩"
      help: "&f/scp help &8- &7This help menu."
      reload: "&f/scp reload &8- &7Reloads config file."
      version: "&f/scp version &8- &7Checks the plugin version and updates."
      checkslime: "&f/scp checkslime &8- &7To get the information of slime chunks."
    slimeChunkFound: "&e在此處發現史萊姆黏液！"
    slimeChunkNotFound: "&f此處沒有發現史萊姆黏液！"
    slimeChunkNearInfo: "&e附近有 &6%amount%個 &e區域檢測到些微黏液 &7(最近距離: %distance%格)"
    slimeChunkNearInfoNull: "&c附近沒有任何史萊姆的氣息..."