# ░░░░░░░░░░░░░░░   SlimeChunkPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/slimechunkplus.85995/
#  Wiki: https://github.com/momoservertw/SlimeChunkPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 1
Check-Updates: true
Debugging: false

General:
  Sounds:
    Succeed:
      Type: ENTITY_PLAYER_LEVELUP
    Failed:
      Type: ENTITY_SHULKER_HURT
    SlimeJump:
      Type: ENTITY_SLIME_JUMP
      Loop:
        Times: 8
        Interval: 20
  Particles:
    Slime:
      Type: SLIME
      Amount: 3
      Times: 8
      Interval: 20

# Checking the nearby slime chunk.
# More information: https://github.com/momoservertw/SlimeChunkPlus/wiki/Slime-Chunk
Slime-Chunk:
  Enable: true
  Succeed:
    Message: true
    Sounds:
      - Succeed
      - SlimeJump
    Particles:
      - Slime
    # Sending nearby slime chunks information.
    Nearby-Information:
      Enable: true
      # Unit: chunk
      Range: 3
    Commands: [ ]
    # To display current chunk by Selection Visualizer.
    #  - "op: svis chunk"
  Failed:
    Message: true
    Sounds:
      - Failed
    Particles: [ ]
    Commands: [ ]

Message:
  prefix: "&f[&aSLP&f] &r"
  noPermission: "&cYou do not have permission to use that command!"
  configReload: "&aConfiguration(s) Reloaded!"
  unknownCommand: "&cUnknown command, See &e/SlimeChunkPlus help &cfor a list of commands."
  targetNotFound: "&cThe player %targetplayer% could not be found!"
  featureDisabled: "&cThe feature is disabled."
  onlyPlayer: "&cThis command can only executing from player."
  SlimeChunkPlus:
    Commands:
      title: "&8▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩ &dSlimeChunkPlus &8▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩"
      help: "&f/scp help &8- &7This help menu."
      reload: "&f/scp reload &8- &7Reloads config file."
      version: "&f/scp version &8- &7Checks the plugin version and updates."
      checkslime: "&f/scp checkslime &8- &7To get the information of slime chunks."
    slimeChunkFound: "&aYou are standing on a slime chunk."
    slimeChunkNotFound: "&fYou are not standing on a slime chunk."
    slimeChunkNearInfo: "&eThere are &6%amount% slime blocks &enearby you. &7(Distance: %distance%)"
    slimeChunkNearInfoNull: "&cThere is no slime block nearby you."